version: '3'
services:
  frontend:
    container_name: react-vite
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/home/node/app/
    ports:
      - 5173:5173
